### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null 报错

### ISSUE THREAD

**Issue by momo-404nf** [MikeCoder/hexo-blog-encrypt#148]
界面方面，在Chrome上进入文章页后能正常显示，但输入密码、敲击回车后无任何反应，查阅控制台发现如下报错：
![QQ截图20200921162430](https://user-images.githubusercontent.com/24471713/93746172-459c0b80-fc27-11ea-8af0-70e7d800ee07.png)
不太懂前端，貌似是没定位到输入密码的元素？而且，如果使用edge浏览器的话，元素会发生偏移重叠：
![QQ截图20200921162750](https://user-images.githubusercontent.com/24471713/93746520-d1159c80-fc27-11ea-8851-db2b5f183b18.png)

个人的 `_config,yaml` 配置如下，本意是为两个标签添加密码，且保持markdown的整洁性，目前没有在任何的文章title上进行过配置，不过我想这应该不影响大局：
```
# hexo-blog-encrypt
encrypt: 
  abstract: 加密文章，请联系管理员获取密码.
  message: 您好, 请输入密码.
  tags:
  - {name: openBMC, password: "helloworld"}
  - {name: Bitbake, password: "helloworld"}
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 密码错误.
  wrong_hash_message: 哈希未通过.
```
我想会不会是和我用的主题冲突了，目前使用的主题是比较少人用的[hexo-theme-inside](https://github.com/ikeq/hexo-theme-inside)
